### ISSUE TITLE
Dropbox link crashes the downloader

### ISSUE THREAD

**Issue by bathrobehero** [Emersont1/itchio#11]
Hey, great tool! I'm trying to download my library but it always crashes at a game that only has a dropbox link for download.

Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\site-packages\itchio\downloader\__main__.py", line 26, in <module>
    lib.download_library()
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\site-packages\itchio\library.py", line 32, in download_library
    game.download(self.login)
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\site-packages\itchio\game.py", line 62, in download
    itchio.utils.download(url, path, self.name +" - "+file)
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\site-packages\itchio\utils.py", line 11, in download
    filename = re.search(r'filename="(.+)"', cd).group(1)
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\re.py", line 199, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

Since there's no way to remove games from the library, could you please add a way to ignore games with dropbox links?

The only workaround I've found is to create a .json file with the name of the game so that the downloader skips it.

**Comment by ThisIsTenou** [comment]
I just encountered the same issue. Happened for the "Spell Slingers: Trick or Treat" game. I assume this issue will become more prominent soon as it's a part of the Ukraine support bundle.

**Comment by ThisIsTenou** [comment]
@bathrobehero Would you mind sharing more details about your workaround? I'm struggling to get the right content into my jsonfile.

**Comment by bathrobehero** [comment]
@ThisIsTenou The .json file can be empty, it's just have to exist under the right subfolder and with the right game name.

**Comment by ThisIsTenou** [comment]
Oh neat! Thank you.

**Comment by ashpieboop** [comment]
#9 should fix this once merged

**Comment by bassclarinetl2** [comment]
> #9 should fix this once merged

Cloning the repo, manually applying the patch in the PR,  and then running ```pip install .``` from the root of the repo should get in working until the PR is merged.  (At leased it worked for me)

**Comment by ThisIsTenou** [comment]
I've made my fork with the fix applied public. Feel free to use that one:
`pip install git+https://github.com/ThisIsTenou/itchio`

**Comment by Emersont1** [comment]
I'll merge in the fix in pronto, as yeah, i've just noticed it

**Comment by Emersont1** [comment]
Fixed with merge of #17 closing
