### ISSUE TITLE
KeyError: 'uploads'

### ISSUE THREAD

**Issue by Zageron** [Emersont1/itchio#13]
```bash
Downloading Zeph - Zeph Final Build.zip
[################################] 530139/530139 - 00:00:55
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zageron/.local/lib/python3.9/site-packages/itchio/downloader/__main__.py", line 26, in <module>
    lib.download_library()
  File "/home/zageron/.local/lib/python3.9/site-packages/itchio/library.py", line 32, in download_library
    game.download(self.login)
  File "/home/zageron/.local/lib/python3.9/site-packages/itchio/game.py", line 39, in download
    self.load_downloads(token)
  File "/home/zageron/.local/lib/python3.9/site-packages/itchio/game.py", line 31, in load_downloads
    for d in j["uploads"]:
KeyError: 'uploads'
```

After starting again, it skipped allthe way to Zeph and then continued. It made it about about 650 downloads before this crash.

**Comment by Emersont1** [comment]
I encountered this breifly yesterday, but I ran again later and there wasn't an issue. I'm afraid I can't seem to reproduce it to debug it. All I can suggest is waiting a few hours and trying agin

**Comment by ashpieboop** [comment]
I ran into a similar issue multiple time yesterday, it could use being handled. However it did run flawlessly over night (an extended period of time), so all in all I'd say it's not a high priority issue.

**Comment by Zageron** [comment]
Yes I have now been also running overnight with no repeat.
