### ISSUE TITLE
Getting RuntimeError on login

### ISSUE THREAD

**Issue by lroellin** [Emersont1/itchio#22]
❯ python3 -m itchiodl.downloader
Username: [redacted]
Password: [typed in, tried pasting, it's really correct]
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/itchiodl/downloader/__main__.py", line 20, in <module>
    l = itchiodl.LoginAPI(user, password)
  File "/usr/local/lib/python3.9/site-packages/itchiodl/login.py", line 30, in LoginAPI
    raise RuntimeError
RuntimeError

**Comment by Emersont1** [comment]
Have you tried with an API key?

**Comment by Emersont1** [comment]
Hi @lroellin I'm just pushing v1.2.1, this should give more detail on the error. If you could post it, censoring any secret data, that would be smashing, and hopefully I can resolve this

**Comment by lroellin** [comment]
Hi @Emersont1, I just tried with the latest version... and it works again :) don't know what went wrong there. Thx for the improvement! (I checked with a wrong password and I could see the output there properly)

**Comment by Emersont1** [comment]
Not too sure what happened there, I know there was an issue with datacentre IPs requiring a captcha to work in other issues
