### ISSUE TITLE
Running into error while trying to add all items in a bundle to my account

### ISSUE THREAD

**Issue by Technerder** [Emersont1/itchio#34]
```output
C:\Users\Username\Desktop\ItchioGames>python -m itchiodl.bundle_tool
Username: removed
Password:
Bundle URL: removed
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\itchiodl\bundle_tool\__main__.py", line 17, in <module>
    main()
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\itchiodl\bundle_tool\__main__.py", line 13, in main
    b.load_games()
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\itchiodl\bundle.py", line 15, in load_games
    pages = int(s.select("span.pager_label a")[-1].text)
IndexError: list index out of range
```

Extra info: I am not using 2FA, just username and password

How can I fix this?

**Comment by jacobbs** [comment]
I suspect itch.io changed the HTML.  I edited the [-1] to [0] in bundle.py and it worked.

**Comment by Emersont1** [comment]
That's odd
as `[-1]` selects the last one

**Comment by frostblooded** [comment]
I was getting a similar error when pasting a wrong link for the bundle. It worked when I added a link that looks like this "https://itch.io/bundle/download/...". You can get that link from My Library -> My Purchases -> Bundles -> Click on the desired bundle -> Copy the link you are currently at.

**Comment by Emersont1** [comment]
Okay, I'll improve documentation if this is ambiguous about the link to be used
